[package]
name = "compute_logger"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = "^0.4.38"
log = "^0.4.22"
serde_json = "^1.0.132"

[dev-dependencies]
mockall = "^0.13.0"
